name: saramitnayo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: ^1.20.0
  flutter_native_splash: 2.2.6
  cloud_firestore: 3.4.2
  flutter_svg: 1.1.1+1
  flutter_neumorphic: 3.2.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/icons/
  uses-material-design: true

